### ISSUE TITLE
Map flipping

### ISSUE THREAD

**Issue by linusivar** [driderr/Trimpz#2]
I see you attempted to fix this issue, this is happening to me couple times per run and i would just like to tell you what i think is happening. Just In case it helps you solve this issue.

In my experience this occurs when I'm running maps and "bot" decides to progress. 

Lets say its doing a Map 50, but then decides it got enough equipment to progress trough world 50(Without finishing the map 50) and comes into world 51 it jumps into maps to farm equipment, it creates a 51 map but have not yet completed the old 50 map. Bot does not detect that it have a old map 50 still active and not finished yet, so attempting to run the new map almost endlessly.

Solutions could be to always finish maps before progressing or implement a detection to finish unfinished maps.

However i think you already knew all this and the possible solutions, but i just wanted to give my thoughts on what i think is causing the flipping, to contribute with something to this awesome script. Great script and keep up the good work.

**Comment by driderr** [comment]
I appreciate your brainstorming because I actually have no idea  why it's happening, and I can use any help I can get on this one.  It's a big problem, and I can never catch it when I single step through the code (so maybe it's a race condition with the game).  The script should _never_ jump out of a map because I have it not do any map code at all when it's running a map.  In other words, at the beginning of the routine RunMaps(), there's a return if maps are running (so no map buttons being hit).  Right now, all of the logic of where the script determines where the player is (map,zone,map screen) is based on two variables from the game: game.global.mapsActive and game.global.preMapsActive.

Unfortunately, your solution won't work because it should never be abandoning maps in the first place.  The other really strange thing is with the way I wrote the code it should run the active map even if it selects the wrong one first.  In other words, it clicks the desired map and then hits the Run/Continue button, which would run the active map regardless.

If anyone wants to help on this one, I'd be very appreciative.

**Comment by driderr** [comment]
After hours of banging my head on this, one thing I tried actually helped a little.  I thought that maybe the switch to map was getting queued and then somehow the map is run directly from "world".  It turned out that that may actually be the issue.  When that happens, the switch stays in the queue until during the map run the soldiers die.  Anyway, this prevents the map flipping from including an actual map, but it does not prevent the flipping between the World and the PreMaps screens.

**Comment by driderr** [comment]
Please reopen the issue if you see any more map flipping when using the latest commit/fix.  If your map bonus is full and it ran a loot map, there are several reasons for it go back to loot map runs during one world level: 
- Your damage dropped from an equipment upgrade.
- Your damage dropped from a lower breed time for Anticipation.
