### ISSUE TITLE
Getting stuck on map screen

### ISSUE THREAD

**Issue by JourneyOver** [driderr/Trimpz#5]
Pretty much what the topic title is, I refreshed the trimps page because I seen you updated the script and now I'm getting stuck on the map screen when ever the script tries to go back to the world screen.

**Comment by driderr** [comment]
I was experiencing this issue before the fix, but I've been running several instances of the game/script ever since and haven't seen it again.  If you're using the latest version and are still seeing it, please link your save game and screen shot of "Trimpz" settings (you can drag files into comments on github).

**Comment by JourneyOver** [comment]
The script seems to have fixed itself or something, just woke up and its running just fine without getting stuck.. Dunno what was up with the issue of it getting stuck on the map screen before :x anyways I'm closing this.
