### ISSUE TITLE
Housing improvement

### ISSUE THREAD

**Issue by dacas3** [driderr/Trimpz#7]
the rate it buys houses at in early game is a bit agressive. is there a way to let us limit the rate it buys housing at, or put a max limit?

Thanks in advance

**Comment by driderr** [comment]
The script uses different ratios for everything that change once certain world zones are hit.  In the beginning, the script will purchase any housing if it only costs 30% of your current resources.  The ratio decreases a few times until Zone 60, where it becomes 0% (won't buy normal housing).

There is a building queue check to make sure building housing doesn't dominate the building queue.  Also, there is a lot of math involved in making sure that an appropriate number of trimps are held back for breeding instead of instantly assigned to jobs.  This makes sure that progress is streamlined even though you may not actually fill up housing for a very long time.  Finally, that can also be helpful if you use the Anticipation perk.

Does this answer your question or are you still desiring changes?

**Comment by dacas3** [comment]
My issue was that it purchaced housing well into the 70-80's amounts, and 30% here and there does add up, without actually contributing any substantial amount of trimp housing. But no, it was merely a suggestion, it doesn't have to happen :)
